wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.2
    cli_version: 0.17.9
    framework: huggingface
    huggingface_version: 4.44.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1725702996
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      - 71
      - 95
      - 97
      - 105
      2:
      - 1
      - 11
      - 49
      - 55
      - 71
      - 95
      - 97
      - 105
      3:
      - 23
      4: 3.11.2
      5: 0.17.9
      6: 4.44.2
      8:
      - 5
      13: linux-x86_64
